# Job runs at 11:15 UTC (6:15AM ET) and at 23:15 UTC (6:15PM ET) everyday!

name: Validate curated tickers with Yahoo API

on:
  schedule:
    - cron: "15 11,23 * * *"

jobs:
  validate_tickers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Validate tickers with Yahoo
        run: npm run get_yahoo
      - name: Commit changes to save state
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Ticker Validator Github Bot
          author_email: laksh47@protonmail.com
          message: "Updating yahoo_validations json files"
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
